### PR TITLE
Create mini VPC for htan-dev

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
This mini VPC will host the pre-production DSA server. I've already added the CIDR to the [Sage VPN table](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/352976898/Sage+VPN). 

Could this be reviewed by @zaro0508 and @ahayden? I've invited you as admins on the repo so you have control in case something catastrophic happens.

### CODE REVIEW

**Review by zaro0508 — APPROVED** [review]

**Review by ahayden — CHANGES_REQUESTED** [review]
Please move any CI into a repo within a Sage organization.

**Comment by BrunoGrandePhD** [comment]
I've invited everyone in Sage IT to the @ncihtan/sage-bionetworks-it team. This team has admin access on this repository.

**Comment by BrunoGrandePhD** [comment]
@ahayden has [indicated](https://sagebionetworks.slack.com/archives/CEFQD0KU1/p1622143661418900) that he sees no other issues with this PR. I'm going to merge it now that the repo has been moved under the Sage-Bionetworks organization.

**Review by ahayden — COMMENTED** [review]
confirmed approved

**Pull request merged**
